# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
admin = Role.create(name:"admin")
teacher = Role.create(name:"teacher")
student = Role.create(name:"student")
# password and confirmation have to be 8 characters or longer or this will not create a user

Country.create(name:"Afghanistan",iso_code:"AF")
Country.create(name:"Åland Islands",iso_code:"AX")
Country.create(name:"Albania",iso_code:"AL")
Country.create(name:"Algeria",iso_code:"DZ")
Country.create(name:"American Samoa",iso_code:"AS")
Country.create(name:"Andorra",iso_code:"AD")
Country.create(name:"Angola",iso_code:"AO")
Country.create(name:"Anguilla",iso_code:"AI")
Country.create(name:"Antarctica",iso_code:"AQ")
Country.create(name:"Antigua and Barbuda",iso_code:"AG")
Country.create(name:"Argentina",iso_code:"AR")
Country.create(name:"Armenia",iso_code:"AM")
Country.create(name:"Aruba",iso_code:"AW")
Country.create(name:"Australia",iso_code:"AU")
Country.create(name:"Austria",iso_code:"AT")
Country.create(name:"Azerbaijan",iso_code:"AZ")
Country.create(name:"Bahamas",iso_code:"BS")
Country.create(name:"Bahrain",iso_code:"BH")
Country.create(name:"Bangladesh",iso_code:"BD")
Country.create(name:"Barbados",iso_code:"BB")
Country.create(name:"Belarus",iso_code:"BY")
Country.create(name:"Belgium",iso_code:"BE")
Country.create(name:"Belize",iso_code:"BZ")
Country.create(name:"Benin",iso_code:"BJ")
Country.create(name:"Bermuda",iso_code:"BM")
Country.create(name:"Bhutan",iso_code:"BT")
Country.create(name:"Bolivia, Plurinational State of",iso_code:"BO")
Country.create(name:"Bonaire, Sint Eustatius and Saba",iso_code:"BQ")
Country.create(name:"Bosnia and Herzegovina",iso_code:"BA")
Country.create(name:"Botswana",iso_code:"BW")
Country.create(name:"Bouvet Island",iso_code:"BV")
Country.create(name:"Brazil",iso_code:"BR")
Country.create(name:"British Indian Ocean Territory",iso_code:"IO")
Country.create(name:"Brunei Darussalam",iso_code:"BN")
Country.create(name:"Bulgaria",iso_code:"BG")
Country.create(name:"Burkina Faso",iso_code:"BF")
Country.create(name:"Burundi",iso_code:"BI")
Country.create(name:"Cambodia",iso_code:"KH")
Country.create(name:"Cameroon",iso_code:"CM")
Country.create(name:"Canada",iso_code:"CA")
Country.create(name:"Cape Verde",iso_code:"CV")
Country.create(name:"Cayman Islands",iso_code:"KY")
Country.create(name:"Central African Republic",iso_code:"CF")
Country.create(name:"Chad",iso_code:"TD")
Country.create(name:"Chile",iso_code:"CL")
Country.create(name:"China",iso_code:"CN")
Country.create(name:"Christmas Island",iso_code:"CX")
Country.create(name:"Cocos (Keeling) Islands",iso_code:"CC")
Country.create(name:"Colombia",iso_code:"CO")
Country.create(name:"Comoros",iso_code:"KM")
Country.create(name:"Congo",iso_code:"CG")
Country.create(name:"Congo, the Democratic Republic of the",iso_code:"CD")
Country.create(name:"Cook Islands",iso_code:"CK")
Country.create(name:"Costa Rica",iso_code:"CR")
Country.create(name:"Côte d'Ivoire",iso_code:"CI")
Country.create(name:"Croatia",iso_code:"HR")
Country.create(name:"Cuba",iso_code:"CU")
Country.create(name:"Curaçao",iso_code:"CW")
Country.create(name:"Cyprus",iso_code:"CY")
Country.create(name:"Czech Republic",iso_code:"CZ")
Country.create(name:"Denmark",iso_code:"DK")
Country.create(name:"Djibouti",iso_code:"DJ")
Country.create(name:"Dominica",iso_code:"DM")
Country.create(name:"Dominican Republic",iso_code:"DO")
Country.create(name:"Ecuador",iso_code:"EC")
Country.create(name:"Egypt",iso_code:"EG")
Country.create(name:"El Salvador",iso_code:"SV")
Country.create(name:"Equatorial Guinea",iso_code:"GQ")
Country.create(name:"Eritrea",iso_code:"ER")
Country.create(name:"Estonia",iso_code:"EE")
Country.create(name:"Ethiopia",iso_code:"ET")
Country.create(name:"Falkland Islands (Malvinas)",iso_code:"FK")
Country.create(name:"Faroe Islands",iso_code:"FO")
Country.create(name:"Fiji",iso_code:"FJ")
Country.create(name:"Finland",iso_code:"FI")
Country.create(name:"France",iso_code:"FR")
Country.create(name:"French Guiana",iso_code:"GF")
Country.create(name:"French Polynesia",iso_code:"PF")
Country.create(name:"French Southern Territories",iso_code:"TF")
Country.create(name:"Gabon",iso_code:"GA")
Country.create(name:"Gambia",iso_code:"GM")
Country.create(name:"Georgia",iso_code:"GE")
Country.create(name:"Germany",iso_code:"DE")
Country.create(name:"Ghana",iso_code:"GH")
Country.create(name:"Gibraltar",iso_code:"GI")
Country.create(name:"Greece",iso_code:"GR")
Country.create(name:"Greenland",iso_code:"GL")
Country.create(name:"Grenada",iso_code:"GD")
Country.create(name:"Guadeloupe",iso_code:"GP")
Country.create(name:"Guam",iso_code:"GU")
Country.create(name:"Guatemala",iso_code:"GT")
Country.create(name:"Guernsey",iso_code:"GG")
Country.create(name:"Guinea",iso_code:"GN")
Country.create(name:"Guinea-Bissau",iso_code:"GW")
Country.create(name:"Guyana",iso_code:"GY")
Country.create(name:"Haiti",iso_code:"HT")
Country.create(name:"Heard Island and McDonald Islands",iso_code:"HM")
Country.create(name:"Holy See (Vatican City State)",iso_code:"VA")
Country.create(name:"Honduras",iso_code:"HN")
Country.create(name:"Hong Kong",iso_code:"HK")
Country.create(name:"Hungary",iso_code:"HU")
Country.create(name:"Iceland",iso_code:"IS")
Country.create(name:"India",iso_code:"IN")
Country.create(name:"Indonesia",iso_code:"ID")
Country.create(name:"Iran, Islamic Republic of",iso_code:"IR")
Country.create(name:"Iraq",iso_code:"IQ")
Country.create(name:"Ireland",iso_code:"IE")
Country.create(name:"Isle of Man",iso_code:"IM")
Country.create(name:"Israel",iso_code:"IL")
Country.create(name:"Italy",iso_code:"IT")
Country.create(name:"Jamaica",iso_code:"JM")
Country.create(name:"Japan",iso_code:"JP")
Country.create(name:"Jersey",iso_code:"JE")
Country.create(name:"Jordan",iso_code:"JO")
Country.create(name:"Kazakhstan",iso_code:"KZ")
Country.create(name:"Kenya",iso_code:"KE")
Country.create(name:"Kiribati",iso_code:"KI")
Country.create(name:"Korea, Democratic People's Republic of",iso_code:"KP")
Country.create(name:"Korea, Republic of",iso_code:"KR")
Country.create(name:"Kuwait",iso_code:"KW")
Country.create(name:"Kyrgyzstan",iso_code:"KG")
Country.create(name:"Lao People's Democratic Republic",iso_code:"LA")
Country.create(name:"Latvia",iso_code:"LV")
Country.create(name:"Lebanon",iso_code:"LB")
Country.create(name:"Lesotho",iso_code:"LS")
Country.create(name:"Liberia",iso_code:"LR")
Country.create(name:"Libya",iso_code:"LY")
Country.create(name:"Liechtenstein",iso_code:"LI")
Country.create(name:"Lithuania",iso_code:"LT")
Country.create(name:"Luxembourg",iso_code:"LU")
Country.create(name:"Macao",iso_code:"MO")
Country.create(name:"Macedonia, the Former Yugoslav Republic of",iso_code:"MK")
Country.create(name:"Madagascar",iso_code:"MG")
Country.create(name:"Malawi",iso_code:"MW")
Country.create(name:"Malaysia",iso_code:"MY")
Country.create(name:"Maldives",iso_code:"MV")
Country.create(name:"Mali",iso_code:"ML")
Country.create(name:"Malta",iso_code:"MT")
Country.create(name:"Marshall Islands",iso_code:"MH")
Country.create(name:"Martinique",iso_code:"MQ")
Country.create(name:"Mauritania",iso_code:"MR")
Country.create(name:"Mauritius",iso_code:"MU")
Country.create(name:"Mayotte",iso_code:"YT")
Country.create(name:"Mexico",iso_code:"MX")
Country.create(name:"Micronesia, Federated States of",iso_code:"FM")
Country.create(name:"Moldova, Republic of",iso_code:"MD")
Country.create(name:"Monaco",iso_code:"MC")
Country.create(name:"Mongolia",iso_code:"MN")
Country.create(name:"Montenegro",iso_code:"ME")
Country.create(name:"Montserrat",iso_code:"MS")
Country.create(name:"Morocco",iso_code:"MA")
Country.create(name:"Mozambique",iso_code:"MZ")
Country.create(name:"Myanmar",iso_code:"MM")
Country.create(name:"Namibia",iso_code:"NA")
Country.create(name:"Nauru",iso_code:"NR")
Country.create(name:"Nepal",iso_code:"NP")
Country.create(name:"Netherlands",iso_code:"NL")
Country.create(name:"New Caledonia",iso_code:"NC")
Country.create(name:"New Zealand",iso_code:"NZ")
Country.create(name:"Nicaragua",iso_code:"NI")
Country.create(name:"Niger",iso_code:"NE")
Country.create(name:"Nigeria",iso_code:"NG")
Country.create(name:"Niue",iso_code:"NU")
Country.create(name:"Norfolk Island",iso_code:"NF")
Country.create(name:"Northern Mariana Islands",iso_code:"MP")
Country.create(name:"Norway",iso_code:"NO")
Country.create(name:"Oman",iso_code:"OM")
Country.create(name:"Pakistan",iso_code:"PK")
Country.create(name:"Palau",iso_code:"PW")
Country.create(name:"Palestine, State of",iso_code:"PS")
Country.create(name:"Panama",iso_code:"PA")
Country.create(name:"Papua New Guinea",iso_code:"PG")
Country.create(name:"Paraguay",iso_code:"PY")
Country.create(name:"Peru",iso_code:"PE")
Country.create(name:"Philippines",iso_code:"PH")
Country.create(name:"Pitcairn",iso_code:"PN")
Country.create(name:"Poland",iso_code:"PL")
Country.create(name:"Portugal",iso_code:"PT")
Country.create(name:"Puerto Rico",iso_code:"PR")
Country.create(name:"Qatar",iso_code:"QA")
Country.create(name:"Réunion",iso_code:"RE")
Country.create(name:"Romania",iso_code:"RO")
Country.create(name:"Russian Federation",iso_code:"RU")
Country.create(name:"Rwanda",iso_code:"RW")
Country.create(name:"Saint Barthélemy",iso_code:"BL")
Country.create(name:"Saint Helena, Ascension and Tristan da Cunha",iso_code:"SH")
Country.create(name:"Saint Kitts and Nevis",iso_code:"KN")
Country.create(name:"Saint Lucia",iso_code:"LC")
Country.create(name:"Saint Martin (French part)",iso_code:"MF")
Country.create(name:"Saint Pierre and Miquelon",iso_code:"PM")
Country.create(name:"Saint Vincent and the Grenadines",iso_code:"VC")
Country.create(name:"Samoa",iso_code:"WS")
Country.create(name:"San Marino",iso_code:"SM")
Country.create(name:"Sao Tome and Principe",iso_code:"ST")
Country.create(name:"Saudi Arabia",iso_code:"SA")
Country.create(name:"Senegal",iso_code:"SN")
Country.create(name:"Serbia",iso_code:"RS")
Country.create(name:"Seychelles",iso_code:"SC")
Country.create(name:"Sierra Leone",iso_code:"SL")
Country.create(name:"Singapore",iso_code:"SG")
Country.create(name:"Sint Maarten (Dutch part)",iso_code:"SX")
Country.create(name:"Slovakia",iso_code:"SK")
Country.create(name:"Slovenia",iso_code:"SI")
Country.create(name:"Solomon Islands",iso_code:"SB")
Country.create(name:"Somalia",iso_code:"SO")
Country.create(name:"South Africa",iso_code:"ZA")
Country.create(name:"South Georgia and the South Sandwich Islands",iso_code:"GS")
Country.create(name:"South Sudan",iso_code:"SS")
Country.create(name:"Spain",iso_code:"ES")
Country.create(name:"Sri Lanka",iso_code:"LK")
Country.create(name:"Sudan",iso_code:"SD")
Country.create(name:"Suriname",iso_code:"SR")
Country.create(name:"Svalbard and Jan Mayen",iso_code:"SJ")
Country.create(name:"Swaziland",iso_code:"SZ")
Country.create(name:"Sweden",iso_code:"SE")
Country.create(name:"Switzerland",iso_code:"CH")
Country.create(name:"Syrian Arab Republic",iso_code:"SY")
Country.create(name:"Taiwan, Province of China",iso_code:"TW")
Country.create(name:"Tajikistan",iso_code:"TJ")
Country.create(name:"Tanzania, United Republic of",iso_code:"TZ")
Country.create(name:"Thailand",iso_code:"TH")
Country.create(name:"Timor-Leste",iso_code:"TL")
Country.create(name:"Togo",iso_code:"TG")
Country.create(name:"Tokelau",iso_code:"TK")
Country.create(name:"Tonga",iso_code:"TO")
Country.create(name:"Trinidad and Tobago",iso_code:"TT")
Country.create(name:"Tunisia",iso_code:"TN")
Country.create(name:"Turkey",iso_code:"TR")
Country.create(name:"Turkmenistan",iso_code:"TM")
Country.create(name:"Turks and Caicos Islands",iso_code:"TC")
Country.create(name:"Tuvalu",iso_code:"TV")
Country.create(name:"Uganda",iso_code:"UG")
Country.create(name:"Ukraine",iso_code:"UA")
Country.create(name:"United Arab Emirates",iso_code:"AE")
Country.create(name:"United Kingdom",iso_code:"GB")
Country.create(name:"United States",iso_code:"US")
Country.create(name:"United States Minor Outlying Islands",iso_code:"UM")
Country.create(name:"Uruguay",iso_code:"UY")
Country.create(name:"Uzbekistan",iso_code:"UZ")
Country.create(name:"Vanuatu",iso_code:"VU")
Country.create(name:"Venezuela, Bolivarian Republic of",iso_code:"VE")
Country.create(name:"Viet Nam",iso_code:"VN")
Country.create(name:"Virgin Islands, British",iso_code:"VG")
Country.create(name:"Virgin Islands, U.S.",iso_code:"VI")
Country.create(name:"Wallis and Futuna",iso_code:"WF")
Country.create(name:"Western Sahara",iso_code:"EH")
Country.create(name:"Yemen",iso_code:"YE")
Country.create(name:"Zambia",iso_code:"ZM")
Country.create(name:"Zimbabwe",iso_code:"ZW")

Organization.create(name:"Gigapan Administrators",city:"Portage",state:"MI", country_id: "236")
User.create(username:"batman", first_name: "bat", password:"password",password_confirmation:"password",email:"batman@gothamcity.net", organization_id: "1") 
UserRole.create(user_id: User.first.id,role_id: Role.first.id)  
User.create(username:"robin", first_name: "robin",password:"password",password_confirmation:"password",email:"robin@gothamcity.net", organization_id: "1") 
UserRole.create(user_id: User.second.id,role_id: Role.second.id)  
User.create(username:"bruce", first_name: "bruce",password:"password",password_confirmation:"password",email:"bruce@gothamcity.net", organization_id: "1") 
UserRole.create(user_id: User.third.id,role_id: Role.third.id)  